apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-world
spec:
  replicas: 2  # Podの数を指定
  selector:
    matchLabels:
      app: flask-hello-world
  template:
    metadata:
      labels:
        app: flask-hello-world
    spec:
      containers:
      - name: flask-hello-world
        image: "${ECR_IMAGE_URL}"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"    
            memory: "128Mi" 
          limits:
            cpu: "200m"     
            memory: "256Mi" 
